version: "3"
services:
  postgres:
    container_name: find_your_pet_pg
    image: postgres
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      DB_NAME: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
  
  mongo_db:
    image: mongo
    container_name: find_your_pet_mongo
    environment: 
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "27017-27019:27017-27019"
    restart: unless-stopped
